<?php

/**
 * TrainingRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrainingRequestTable extends PluginTrainingRequestTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrainingRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrainingRequest');
    }
}