<?php

/**
 * PluginPretImmobilierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPretImmobilierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPretImmobilierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPretImmobilier');
    }
}