<?php

/**
 * PluginVehiculeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVehiculeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVehiculeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVehicule');
    }
}