<?php

/**
 * PluginKpiGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKpiGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginKpiGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginKpiGroup');
    }
}