<?php

/**
 * PluginCommentaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCommentaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCommentaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCommentaire');
    }
}