<?php

/**
 * BaseCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kpi_id
 * @property integer $rating_id
 * @property clob $comment
 * @property string $mois
 * @property ReviewerRating $reviewerRating
 * @property Kpi $kpi
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getKpiId()          Returns the current record's "kpi_id" value
 * @method integer        getRatingId()       Returns the current record's "rating_id" value
 * @method clob           getComment()        Returns the current record's "comment" value
 * @method string         getMois()           Returns the current record's "mois" value
 * @method ReviewerRating getReviewerRating() Returns the current record's "reviewerRating" value
 * @method Kpi            getKpi()            Returns the current record's "kpi" value
 * @method Commentaire    setId()             Sets the current record's "id" value
 * @method Commentaire    setKpiId()          Sets the current record's "kpi_id" value
 * @method Commentaire    setRatingId()       Sets the current record's "rating_id" value
 * @method Commentaire    setComment()        Sets the current record's "comment" value
 * @method Commentaire    setMois()           Sets the current record's "mois" value
 * @method Commentaire    setReviewerRating() Sets the current record's "reviewerRating" value
 * @method Commentaire    setKpi()            Sets the current record's "kpi" value
 * 
 * @package    orangehrm
 * @subpackage model\performance\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommentaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_commentaire');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('kpi_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('rating_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('comment', 'clob', 65532, array(
             'type' => 'clob',
             'length' => 65532,
             ));
        $this->hasColumn('mois', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ReviewerRating as reviewerRating', array(
             'local' => 'rating_id',
             'foreign' => 'id'));

        $this->hasOne('Kpi as kpi', array(
             'local' => 'kpi_id',
             'foreign' => 'id'));
    }
}