<?php

/**
 * BasePretImmobilier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Decimal $montant_pret
 * @property string $objet
 * @property integer $nombre_mois
 * @property date $date_accord
 * @property date $date_prelevement
 * @property Decimal $quotite_saisissable
 * @property integer $emp_number
 * @property blob $filecontent
 * @property string $filename
 * @property string $filetype
 * @property integer $filesize
 * @property Employee $Employee
 * 
 * @method integer        getId()                  Returns the current record's "id" value
 * @method Decimal        getMontantPret()         Returns the current record's "montant_pret" value
 * @method string         getObjet()               Returns the current record's "objet" value
 * @method integer        getNombreMois()          Returns the current record's "nombre_mois" value
 * @method date           getDateAccord()          Returns the current record's "date_accord" value
 * @method date           getDatePrelevement()     Returns the current record's "date_prelevement" value
 * @method Decimal        getQuotiteSaisissable()  Returns the current record's "quotite_saisissable" value
 * @method integer        getEmpNumber()           Returns the current record's "emp_number" value
 * @method blob           getFilecontent()         Returns the current record's "filecontent" value
 * @method string         getFilename()            Returns the current record's "filename" value
 * @method string         getFiletype()            Returns the current record's "filetype" value
 * @method integer        getFilesize()            Returns the current record's "filesize" value
 * @method Employee       getEmployee()            Returns the current record's "Employee" value
 * @method PretImmobilier setId()                  Sets the current record's "id" value
 * @method PretImmobilier setMontantPret()         Sets the current record's "montant_pret" value
 * @method PretImmobilier setObjet()               Sets the current record's "objet" value
 * @method PretImmobilier setNombreMois()          Sets the current record's "nombre_mois" value
 * @method PretImmobilier setDateAccord()          Sets the current record's "date_accord" value
 * @method PretImmobilier setDatePrelevement()     Sets the current record's "date_prelevement" value
 * @method PretImmobilier setQuotiteSaisissable()  Sets the current record's "quotite_saisissable" value
 * @method PretImmobilier setEmpNumber()           Sets the current record's "emp_number" value
 * @method PretImmobilier setFilecontent()         Sets the current record's "filecontent" value
 * @method PretImmobilier setFilename()            Sets the current record's "filename" value
 * @method PretImmobilier setFiletype()            Sets the current record's "filetype" value
 * @method PretImmobilier setFilesize()            Sets the current record's "filesize" value
 * @method PretImmobilier setEmployee()            Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\performance\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePretImmobilier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_pretimmobilier');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('montant_pret', 'Decimal', 65, array(
             'type' => 'Decimal',
             'length' => 65,
             'scale' => '0',
             ));
        $this->hasColumn('objet', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('nombre_mois', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('date_accord', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_prelevement', 'date', 25, array(
             'type' => 'date',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('quotite_saisissable', 'Decimal', 65, array(
             'type' => 'Decimal',
             'length' => 65,
             'scale' => '0',
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('filecontent', 'blob', 2147483647, array(
             'type' => 'blob',
             'notnull' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('filetype', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('filesize', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}