<?php

/**
 * BaseTraining
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cout_formation
 * @property string $title
 * @property date $date_applied
 * @property integer $emp_number
 * @property string $description
 * @property blob $filecontent
 * @property string $filename
 * @property string $filetype
 * @property integer $filesize
 * @property Employee $Employee
 * 
 * @method integer  getId()             Returns the current record's "id" value
 * @method string   getCoutFormation()  Returns the current record's "cout_formation" value
 * @method string   getTitle()          Returns the current record's "title" value
 * @method date     getDateApplied()    Returns the current record's "date_applied" value
 * @method integer  getEmpNumber()      Returns the current record's "emp_number" value
 * @method string   getDescription()    Returns the current record's "description" value
 * @method blob     getFilecontent()    Returns the current record's "filecontent" value
 * @method string   getFilename()       Returns the current record's "filename" value
 * @method string   getFiletype()       Returns the current record's "filetype" value
 * @method integer  getFilesize()       Returns the current record's "filesize" value
 * @method Employee getEmployee()       Returns the current record's "Employee" value
 * @method Training setId()             Sets the current record's "id" value
 * @method Training setCoutFormation()  Sets the current record's "cout_formation" value
 * @method Training setTitle()          Sets the current record's "title" value
 * @method Training setDateApplied()    Sets the current record's "date_applied" value
 * @method Training setEmpNumber()      Sets the current record's "emp_number" value
 * @method Training setDescription()    Sets the current record's "description" value
 * @method Training setFilecontent()    Sets the current record's "filecontent" value
 * @method Training setFilename()       Sets the current record's "filename" value
 * @method Training setFiletype()       Sets the current record's "filetype" value
 * @method Training setFilesize()       Sets the current record's "filesize" value
 * @method Training setEmployee()       Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\performance\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTraining extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cout_formation', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('date_applied', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
        $this->hasColumn('filecontent', 'blob', 2147483647, array(
             'type' => 'blob',
             'notnull' => false,
             'length' => 2147483647,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('filetype', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('filesize', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}