<?php

/**
 * BaseKpiGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kpi_group_name
 * 
 * @method integer  getId()             Returns the current record's "id" value
 * @method string   getKpiGroupName()   Returns the current record's "kpi_group_name" value
 * @method KpiGroup setId()             Sets the current record's "id" value
 * @method KpiGroup setKpiGroupName()   Sets the current record's "kpi_group_name" value
 * 
 * @package    orangehrm
 * @subpackage model\performance\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKpiGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_kpi_group');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('kpi_group_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}