<?php

/**
 * PluginTrainingRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTrainingRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTrainingRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTrainingRequest');
    }
}