<?php

/**
 * CommentaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentaireTable extends PluginCommentaireTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commentaire');
    }
}