<?php

/**
 * KpiGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KpiGroupTable extends PluginKpiGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object KpiGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KpiGroup');
    }
}