<?php

/**
 * PretImmobilierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PretImmobilierTable extends PluginPretImmobilierTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PretImmobilierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PretImmobilier');
    }
}