<?php

/**
 * VehiculeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculeTable extends PluginVehiculeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vehicule');
    }
}